# Generated by Django 2.2 on 2019-04-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
