# Generated by Django 2.2 on 2019-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190426_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
