# Generated by Django 2.2 on 2019-04-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_suborder'),
        ('suborder', '0002_remove_suborder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
