# Generated by Django 2.2 on 2019-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suborder', '0003_auto_20190417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
